from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow():
    def eval_it(self):
        screen = self.output_label.text()
        answer = eval(screen)
        self.output_label.setText(str(answer))
    def plus_minus_it(self):
        screen = self.output_label.text()
        if "-" in screen:
            self.output_label.setText(screen.replace(f"-", ""))
        elif "-" not in screen:
            self.output_label.setText(f"-{screen}")
    def remove_it(self):
        screen = self.output_label.text()
        screen = screen[:-1]
        self.output_label.setText(screen)
    def dot_it(self):
        screen = self.output_label.text()
        possible_chars_list = ['*','/','-','+']
        is_valid = True
        for i in screen:
            if i in possible_chars_list:
                is_valid = True
            elif i == '.':
                is_valid = False
        if is_valid:
            self.output_label.setText(f'{screen}.')
    def press_it(self, pressed):
        if pressed == "C":
            self.output_label.setText("0")
        else:
            if self.output_label.text() == "0":
                self.output_label.setText("")
            self.output_label.setText(f'{self.output_label.text()}{pressed}')
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(325, 491)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.output_label = QtWidgets.QLabel(self.centralwidget)
        self.output_label.setGeometry(QtCore.QRect(10, 10, 304, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.output_label.setFont(font)
        self.output_label.setFrameShape(QtWidgets.QFrame.Box)
        self.output_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.output_label.setLineWidth(1)
        self.output_label.setMidLineWidth(0)
        self.output_label.setTextFormat(QtCore.Qt.AutoText)
        self.output_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.output_label.setIndent(17)
        self.output_label.setObjectName("output_label")
        self.push_button_1 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("%"))
        self.push_button_1.setGeometry(QtCore.QRect(9, 80, 65, 62))
        self.push_button_1.setSizeIncrement(QtCore.QSize(0, 0))
        self.push_button_1.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.push_button_1.setFont(font)
        self.push_button_1.setObjectName("push_button_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("C"))
        self.pushButton_2.setGeometry(QtCore.QRect(89, 80, 65, 62))
        self.pushButton_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_2.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.remove_it())
        self.pushButton_3.setGeometry(QtCore.QRect(169, 80, 65, 62))
        self.pushButton_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_3.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("/"))
        self.pushButton_4.setGeometry(QtCore.QRect(249, 80, 65, 62))
        self.pushButton_4.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_4.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("*"))
        self.pushButton_8.setGeometry(QtCore.QRect(249, 160, 65, 62))
        self.pushButton_8.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_8.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("8"))
        self.pushButton_6.setGeometry(QtCore.QRect(89, 160, 65, 62))
        self.pushButton_6.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_6.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("7"))
        self.pushButton_5.setGeometry(QtCore.QRect(9, 159, 65, 62))
        self.pushButton_5.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_5.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("9"))
        self.pushButton_7.setGeometry(QtCore.QRect(169, 160, 65, 62))
        self.pushButton_7.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_7.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("-"))
        self.pushButton_12.setGeometry(QtCore.QRect(249, 240, 65, 62))
        self.pushButton_12.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_12.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("5"))
        self.pushButton_10.setGeometry(QtCore.QRect(89, 240, 65, 62))
        self.pushButton_10.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_10.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("4"))
        self.pushButton_9.setGeometry(QtCore.QRect(9, 240, 65, 62))
        self.pushButton_9.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_9.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("6"))
        self.pushButton_11.setGeometry(QtCore.QRect(169, 240, 65, 62))
        self.pushButton_11.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_11.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("+"))
        self.pushButton_16.setGeometry(QtCore.QRect(249, 320, 65, 62))
        self.pushButton_16.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_16.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("2"))
        self.pushButton_14.setGeometry(QtCore.QRect(89, 320, 65, 62))
        self.pushButton_14.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_14.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("1"))
        self.pushButton_13.setGeometry(QtCore.QRect(9, 320, 65, 62))
        self.pushButton_13.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_13.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("3"))
        self.pushButton_15.setGeometry(QtCore.QRect(169, 320, 65, 62))
        self.pushButton_15.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_15.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.eval_it())
        self.pushButton_20.setGeometry(QtCore.QRect(249, 400, 65, 62))
        self.pushButton_20.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_20.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_it("0"))
        self.pushButton_18.setGeometry(QtCore.QRect(89, 400, 65, 62))
        self.pushButton_18.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_18.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.plus_minus_it())
        self.pushButton_17.setGeometry(QtCore.QRect(9, 400, 65, 62))
        self.pushButton_17.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_17.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.dot_it())
        self.pushButton_19.setGeometry(QtCore.QRect(169, 400, 65, 62))
        self.pushButton_19.setSizeIncrement(QtCore.QSize(0, 0))
        self.pushButton_19.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.output_label.setText(_translate("MainWindow", "0"))
        self.push_button_1.setText(_translate("MainWindow", "%"))
        self.pushButton_2.setText(_translate("MainWindow", "C"))
        self.pushButton_3.setText(_translate("MainWindow", "<<"))
        self.pushButton_4.setText(_translate("MainWindow", "/"))
        self.pushButton_8.setText(_translate("MainWindow", "*"))
        self.pushButton_6.setText(_translate("MainWindow", "8"))
        self.pushButton_5.setText(_translate("MainWindow", "7"))
        self.pushButton_7.setText(_translate("MainWindow", "9"))
        self.pushButton_12.setText(_translate("MainWindow", "-"))
        self.pushButton_10.setText(_translate("MainWindow", "5"))
        self.pushButton_9.setText(_translate("MainWindow", "4"))
        self.pushButton_11.setText(_translate("MainWindow", "6"))
        self.pushButton_16.setText(_translate("MainWindow", "+"))
        self.pushButton_14.setText(_translate("MainWindow", "2"))
        self.pushButton_13.setText(_translate("MainWindow", "1"))
        self.pushButton_15.setText(_translate("MainWindow", "3"))
        self.pushButton_20.setText(_translate("MainWindow", "="))
        self.pushButton_18.setText(_translate("MainWindow", "0"))
        self.pushButton_17.setText(_translate("MainWindow", "+/-"))
        self.pushButton_19.setText(_translate("MainWindow", "."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
